export const JOBRUN_STATE_DICT = {
  STARTING: "STARTING",
  RUNNING: "RUNNING",
  STOPPING: "STOPPING",
  STOPPED: "STOPPED",
  SUCCEEDED: "SUCCEEDED",
  FAILED: "FAILED",
  TIMEOUT: "TIMEOUT",
  ERROR: "ERROR",
  WAITING: "WAITING",
  EXPIRED: "EXPIRED",
};
